<?php
// Guide de configuration cPanel - Linekode Admin
echo "<!DOCTYPE html>";
echo "<html lang='fr'>";
echo "<head>";
echo "    <meta charset='UTF-8'>";
echo "    <meta name='viewport' content='width=device-width, initial-scale=1.0'>";
echo "    <title>Guide cPanel - Linekode Admin</title>";
echo "    <style>";
echo "        body { font-family: Arial, sans-serif; max-width: 1000px; margin: 50px auto; padding: 20px; }";
echo "        .header { background: linear-gradient(135deg, #ff6b35, #f7931e); color: white; padding: 30px; border-radius: 12px; text-align: center; margin-bottom: 30px; }";
echo "        .step { border: 1px solid #ddd; padding: 25px; margin: 20px 0; border-radius: 12px; background: #f8f9fa; }";
echo "        .step h3 { color: #0284c7; margin-top: 0; font-size: 24px; }";
echo "        .step-number { background: #0284c7; color: white; width: 40px; height: 40px; border-radius: 50%; display: flex; align-items: center; justify-content: center; font-weight: bold; margin-bottom: 15px; }";
echo "        .info { background: #d1ecf1; color: #0c5460; padding: 15px; border-radius: 8px; margin: 10px 0; border-left: 4px solid #0284c7; }";
echo "        .success { background: #d4edda; color: #155724; padding: 15px; border-radius: 8px; margin: 10px 0; border-left: 4px solid #28a745; }";
echo "        .warning { background: #fff3cd; color: #856404; padding: 15px; border-radius: 8px; margin: 10px 0; border-left: 4px solid #ffc107; }";
echo "        .error { background: #f8d7da; color: #721c24; padding: 15px; border-radius: 8px; margin: 10px 0; border-left: 4px solid #dc3545; }";
echo "        .btn { background: #0284c7; color: white; padding: 12px 24px; border: none; border-radius: 6px; cursor: pointer; margin: 5px; text-decoration: none; display: inline-block; }";
echo "        .btn:hover { background: #0369a1; }";
echo "        .btn-success { background: #28a745; }";
echo "        .btn-success:hover { background: #218838; }";
echo "        .btn-warning { background: #ffc107; color: #212529; }";
echo "        .btn-warning:hover { background: #e0a800; }";
echo "        code { background: #f8f9fa; padding: 3px 6px; border-radius: 4px; font-family: 'Courier New', monospace; }";
echo "        .screenshot { border: 2px solid #ddd; border-radius: 8px; margin: 15px 0; max-width: 100%; }";
echo "        .checklist { list-style: none; padding: 0; }";
echo "        .checklist li { padding: 8px 0; border-bottom: 1px solid #eee; }";
echo "        .checklist li:before { content: '✅ '; margin-right: 8px; }";
echo "        .highlight { background: #fff3cd; padding: 15px; border-radius: 8px; border-left: 4px solid #ffc107; margin: 15px 0; }";
echo "    </style>";
echo "</head>";
echo "<body>";

echo "<div class='header'>";
echo "    <h1>🖥️ Guide de Configuration cPanel</h1>";
echo "    <h2>Linekode Admin - Installation MySQL</h2>";
echo "</div>";

echo "<div class='info'>";
echo "<h3>📋 Ce que nous allons configurer:</h3>";
echo "<ul class='checklist'>";
echo "<li>Base de données MySQL: <code>linekode_admin</code></li>";
echo "<li>Utilisateur MySQL: <code>linekode_admin</code></li>";
echo "<li>Mot de passe: <code>linekode2024</code></li>";
echo "<li>Permissions: Tous les privilèges</li>";
echo "</ul>";
echo "</div>";

echo "<div class='step'>";
echo "<div class='step-number'>1</div>";
echo "<h3>🔐 Connexion à cPanel</h3>";
echo "<ol>";
echo "<li>Ouvrez votre navigateur web</li>";
echo "<li>Accédez à votre cPanel avec l'URL fournie par votre hébergeur</li>";
echo "<li>Exemples d'URL cPanel:";
echo "<ul>";
echo "<li><code>https://votredomaine.com:2083</code></li>";
echo "<li><code>https://cpanel.votredomaine.com</code></li>";
echo "<li><code>https://votredomaine.com/cpanel</code></li>";
echo "</ul>";
echo "</li>";
echo "<li>Connectez-vous avec vos identifiants cPanel</li>";
echo "</ol>";
echo "</div>";

echo "<div class='step'>";
echo "<div class='step-number'>2</div>";
echo "<h3>🗄️ Accès aux bases de données MySQL</h3>";
echo "<p>Dans le tableau de bord cPanel, cherchez la section <strong>Databases</strong>:</p>";
echo "<ul>";
echo "<li>Cherchez l'icône <strong>MySQL Databases</strong></li>";
echo "<li>Si vous ne la trouvez pas, utilisez la barre de recherche en haut</li>";
echo "<li>Cliquez sur <strong>MySQL Databases</strong></li>";
echo "</ul>";
echo "<div class='highlight'>";
echo "<strong>💡 Astuce:</strong> L'icône MySQL Databases est généralement dans la section Databases avec une icône de base de données bleue.";
echo "</div>";
echo "</div>";

echo "<div class='step'>";
echo "<div class='step-number'>3</div>";
echo "<h3>📦 Création de la base de données</h3>";
echo "<p>Dans la page MySQL Databases:</p>";
echo "<ol>";
echo "<li>Cherchez la section <strong>Create New Database</strong></li>";
echo "<li>Dans le champ <strong>New Database</strong>, tapez: <code>linekode_admin</code></li>";
echo "<li>Cliquez sur <strong>Create Database</strong></li>";
echo "<li>Vous devriez voir un message de confirmation: <em>Database linekode_admin created successfully</em></li>";
echo "</ol>";
echo "<div class='success'>";
echo "<strong>✅ Succès:</strong> La base de données est maintenant créée!";
echo "</div>";
echo "</div>";

echo "<div class='step'>";
echo "<div class='step-number'>4</div>";
echo "<h3>👤 Création de l'utilisateur MySQL</h3>";
echo "<p>Dans la même page MySQL Databases:</p>";
echo "<ol>";
echo "<li>Faites défiler vers le bas jusqu'à la section <strong>MySQL Users</strong></li>";
echo "<li>Dans le champ <strong>Username</strong>, tapez: <code>linekode_admin</code></li>";
echo "<li>Dans le champ <strong>Password</strong>, tapez: <code>linekode2024</code></li>";
echo "<li>Cochez <strong>Generate Password</strong> si vous voulez un mot de passe plus sécurisé</li>";
echo "<li>Cliquez sur <strong>Create User</strong></li>";
echo "<li>Notez bien le mot de passe généré si vous utilisez cette option</li>";
echo "</ol>";
echo "<div class='warning'>";
echo "<strong>⚠️ Important:</strong> Gardez votre mot de passe en sécurité. Si vous utilisez un mot de passe différent, vous devrez le noter pour la suite.";
echo "</div>";
echo "</div>";

echo "<div class='step'>";
echo "<div class='step-number'>5</div>";
echo "<h3>🔐 Ajout des permissions à l'utilisateur</h3>";
echo "<p>Dans la section <strong>Add User to Database</strong>:</p>";
echo "<ol>";
echo "<li>Dans le menu déroulant <strong>User</strong>, sélectionnez <code>linekode_admin</code></li>";
echo "<li>Dans le menu déroulant <strong>Database</strong>, sélectionnez <code>linekode_admin</code></li>";
echo "<li>Cliquez sur <strong>Add</strong></li>";
echo "</ol>";
echo "<p>Vous arriverez sur la page des permissions:</p>";
echo "<ol start='4'>";
echo "<li>Cochez <strong>ALL PRIVILEGES</strong> (en haut de la liste)</li>";
echo "<li>Cliquez sur <strong>Make Changes</strong></li>";
echo "<li>Vous devriez voir un message de confirmation</li>";
echo "</ol>";
echo "<div class='success'>";
echo "<strong>✅ Succès:</strong> L'utilisateur a maintenant tous les droits sur la base de données!";
echo "</div>";
echo "</div>";

echo "<div class='step'>";
echo "<div class='step-number'>6</div>";
echo "<h3>✅ Vérification de la configuration</h3>";
echo "<p>Retournez à la page MySQL Databases et vérifiez:</p>";
echo "<ul class='checklist'>";
echo "<li>La base de données <code>linekode_admin</code> apparaît dans la liste</li>";
echo "<li>L'utilisateur <code>linekode_admin</code> apparaît dans la liste</li>";
echo "<li>L'utilisateur est bien associé à la base de données</li>";
echo "<li>Les permissions sont bien configurées</li>";
echo "</ul>";
echo "</div>";

echo "<div class='step'>";
echo "<div class='step-number'>7</div>";
echo "<h3>🚀 Installation de Linekode Admin</h3>";
echo "<p>Maintenant que votre base de données est configurée:</p>";
echo "<ol>";
echo "<li>Retournez sur votre site Linekode</li>";
echo "<li>Accédez à: <a href='setup-server.php' class='btn'>setup-server.php</a></li>";
echo "<li>Le système détectera automatiquement votre configuration</li>";
echo "<li>Suivez les instructions d'installation</li>";
echo "</ol>";
echo "<div class='info'>";
echo "<strong>📝 Note:</strong> Le système utilisera automatiquement les identifiants que vous venez de configurer.";
echo "</div>";
echo "</div>";

echo "<div class='step'>";
echo "<div class='step-number'>8</div>";
echo "<h3>🔐 Accès à l'administration</h3>";
echo "<p>Une fois l'installation terminée:</p>";
echo "<ol>";
echo "<li>Accédez à: <a href='login.php' class='btn btn-success'>login.php</a></li>";
echo "<li>Identifiants: <code>admin</code> / <code>linekode2024</code></li>";
echo "<li>Vous accéderez au dashboard de Linekode Admin</li>";
echo "</ol>";
echo "</div>";

echo "<div class='warning'>";
echo "<h3>⚠️ Problèmes courants et solutions:</h3>";
echo "<ul>";
echo "<li><strong>Erreur de connexion:</strong> Vérifiez que l'utilisateur et la base de données sont bien créés</li>";
echo "<li><strong>Permissions refusées:</strong> Assurez-vous d'avoir coché ALL PRIVILEGES</li>";
echo "<li><strong>Base de données non trouvée:</strong> Vérifiez l'orthographe exacte de <code>linekode_admin</code></li>";
echo "<li><strong>Mot de passe incorrect:</strong> Utilisez exactement <code>linekode2024</code> ou notez votre mot de passe personnalisé</li>";
echo "</ul>";
echo "</div>";

echo "<div class='success'>";
echo "<h3>🎉 Félicitations!</h3>";
echo "<p>Vous avez configuré avec succès votre base de données MySQL pour Linekode Admin!</p>";
echo "<p>Vous pouvez maintenant:</p>";
echo "<ul>";
echo "<li>Gérer les inscriptions des étudiants</li>";
echo "<li>Recevoir et répondre aux messages</li>";
echo "<li>Publier des annonces</li>";
echo "<li>Voir les statistiques en temps réel</li>";
echo "</ul>";
echo "</div>";

echo "<div style='margin-top: 40px; text-align: center;'>";
echo "<a href='setup-server.php' class='btn btn-success'>🚀 Lancer l'installation</a>";
echo "<a href='login.php' class='btn'>🔐 Accès admin</a>";
echo "<a href='../index.html' class='btn'>🏠 Retour au site</a>";
echo "</div>";

echo "</body>";
echo "</html>";
?>
