<?php
// Guide cPanel avec images - Linekode Admin
echo "<!DOCTYPE html>";
echo "<html lang='fr'>";
echo "<head>";
echo "    <meta charset='UTF-8'>";
echo "    <meta name='viewport' content='width=device-width, initial-scale=1.0'>";
echo "    <title>Guide cPanel avec Images - Linekode Admin</title>";
echo "    <style>";
echo "        body { font-family: Arial, sans-serif; max-width: 1200px; margin: 30px auto; padding: 20px; }";
echo "        .header { background: linear-gradient(135deg, #ff6b35, #f7931e); color: white; padding: 40px; border-radius: 15px; text-align: center; margin-bottom: 40px; }";
echo "        .step { border: 1px solid #ddd; padding: 30px; margin: 30px 0; border-radius: 15px; background: #f8f9fa; box-shadow: 0 4px 15px rgba(0,0,0,0.1); }";
echo "        .step h3 { color: #0284c7; margin-top: 0; font-size: 28px; }";
echo "        .step-number { background: #0284c7; color: white; width: 50px; height: 50px; border-radius: 50%; display: flex; align-items: center; justify-content: center; font-weight: bold; font-size: 24px; margin-bottom: 20px; }";
echo "        .image-placeholder { background: #e9ecef; border: 2px dashed #adb5bd; border-radius: 10px; padding: 40px; text-align: center; margin: 20px 0; color: #6c757d; }";
echo "        .info { background: #d1ecf1; color: #0c5460; padding: 20px; border-radius: 10px; margin: 15px 0; border-left: 5px solid #0284c7; }";
echo "        .success { background: #d4edda; color: #155724; padding: 20px; border-radius: 10px; margin: 15px 0; border-left: 5px solid #28a745; }";
echo "        .warning { background: #fff3cd; color: #856404; padding: 20px; border-radius: 10px; margin: 15px 0; border-left: 5px solid #ffc107; }";
echo "        .btn { background: #0284c7; color: white; padding: 15px 30px; border: none; border-radius: 8px; cursor: pointer; margin: 5px; text-decoration: none; display: inline-block; font-size: 16px; }";
echo "        .btn:hover { background: #0369a1; }";
echo "        .btn-success { background: #28a745; }";
echo "        .btn-success:hover { background: #218838; }";
echo "        .btn-warning { background: #ffc107; color: #212529; }";
echo "        .btn-warning:hover { background: #e0a800; }";
echo "        code { background: #f8f9fa; padding: 4px 8px; border-radius: 4px; font-family: 'Courier New', monospace; font-size: 14px; }";
echo "        .highlight { background: #fff3cd; padding: 20px; border-radius: 10px; border-left: 5px solid #ffc107; margin: 20px 0; }";
echo "        .two-columns { display: grid; grid-template-columns: 1fr 1fr; gap: 30px; align-items: start; }";
echo "        .screenshot-desc { background: white; padding: 20px; border-radius: 10px; border: 1px solid #ddd; }";
echo "    </style>";
echo "</head>";
echo "<body>";

echo "<div class='header'>";
echo "    <h1>🖥️ Guide cPanel Complet</h1>";
echo "    <h2>Configuration MySQL pour Linekode Admin</h2>";
echo "    <p>Suivez ce guide pas à pas avec images pour configurer votre base de données</p>";
echo "</div>";

echo "<div class='step'>";
echo "<div class='step-number'>1</div>";
echo "<h3>🔐 Connexion à cPanel</h3>";
echo "<div class='two-columns'>";
echo "<div>";
echo "<p><strong>URLs cPanel courantes:</strong></p>";
echo "<ul>";
echo "<li><code>https://votredomaine.com:2083</code></li>";
echo "<li><code>https://cpanel.votredomaine.com</code></li>";
echo "<li><code>https://votredomaine.com/cpanel</code></li>";
echo "</ul>";
echo "<p><strong>Identifiants:</strong></p>";
echo "<ul>";
echo "<li>Nom d'utilisateur: fourni par votre hébergeur</li>";
echo "<li>Mot de passe: fourni par votre hébergeur</li>";
echo "</ul>";
echo "</div>";
echo "<div>";
echo "<div class='image-placeholder'>";
echo "📸 Image: Page de connexion cPanel";
echo "<br><small>Interface de connexion avec champs username/password</small>";
echo "</div>";
echo "</div>";
echo "</div>";
echo "</div>";

echo "<div class='step'>";
echo "<div class='step-number'>2</div>";
echo "<h3>🗄️ Accès à MySQL Databases</h3>";
echo "<div class='two-columns'>";
echo "<div>";
echo "<p>Dans le tableau de bord cPanel:</p>";
echo "<ol>";
echo "<li>Cherchez la section <strong>Databases</strong></li>";
echo "<li>Trouvez l'icône <strong>MySQL Databases</strong></li>";
echo "<li>Cliquez dessus</li>";
echo "</ol>";
echo "<div class='highlight'>";
echo "<strong>💡 Astuce:</strong> Utilisez la barre de recherche en haut et tapez \"MySQL\" pour trouver rapidement.";
echo "</div>";
echo "</div>";
echo "<div>";
echo "<div class='image-placeholder'>";
echo "📸 Image: Tableau de bord cPanel";
echo "<br><small>Section Databases avec l'icône MySQL Databases</small>";
echo "</div>";
echo "</div>";
echo "</div>";
echo "</div>";

echo "<div class='step'>";
echo "<div class='step-number'>3</div>";
echo "<h3>📦 Création de la base de données</h3>";
echo "<div class='two-columns'>";
echo "<div>";
echo "<p>Dans la page MySQL Databases:</p>";
echo "<ol>";
echo "<li>Cherchez <strong>Create New Database</strong></li>";
echo "<li>Tapez: <code>linekode_admin</code></li>";
echo "<li>Cliquez sur <strong>Create Database</strong></li>";
echo "</ol>";
echo "<div class='success'>";
echo "<strong>✅ Message attendu:</strong> \"Database linekode_admin created successfully\"";
echo "</div>";
echo "</div>";
echo "<div>";
echo "<div class='image-placeholder'>";
echo "📸 Image: Formulaire de création de base de données";
echo "<br><small>Champ \"New Database\" avec le bouton \"Create Database\"</small>";
echo "</div>";
echo "</div>";
echo "</div>";
echo "</div>";

echo "<div class='step'>";
echo "<div class='step-number'>4</div>";
echo "<h3>👤 Création de l'utilisateur MySQL</h3>";
echo "<div class='two-columns'>";
echo "<div>";
echo "<p>Dans la section <strong>MySQL Users</strong>:</p>";
echo "<ol>";
echo "<li>Username: <code>linekode_admin</code></li>";
echo "<li>Password: <code>linekode2024</code></li>";
echo "<li>Cochez <strong>Generate Password</strong> (optionnel)</li>";
echo "<li>Cliquez sur <strong>Create User</strong></li>";
echo "</ol>";
echo "<div class='warning'>";
echo "<strong>⚠️ Important:</strong> Si vous générez un mot de passe, notez-le bien! Vous devrez le modifier dans le fichier config-server.php";
echo "</div>";
echo "</div>";
echo "<div>";
echo "<div class='image-placeholder'>";
echo "📸 Image: Formulaire de création d'utilisateur MySQL";
echo "<br><small>Champs Username et Password avec bouton Create User</small>";
echo "</div>";
echo "</div>";
echo "</div>";
echo "</div>";

echo "<div class='step'>";
echo "<div class='step-number'>5</div>";
echo "<h3>🔐 Ajout des permissions</h3>";
echo "<div class='two-columns'>";
echo "<div>";
echo "<p>Dans <strong>Add User to Database</strong>:</p>";
echo "<ol>";
echo "<li>User: <code>linekode_admin</code></li>";
echo "<li>Database: <code>linekode_admin</code></li>";
echo "<li>Cliquez sur <strong>Add</strong></li>";
echo "<li>Cochez <strong>ALL PRIVILEGES</strong></li>";
echo "<li>Cliquez sur <strong>Make Changes</strong></li>";
echo "</ol>";
echo "<div class='success'>";
echo "<strong>✅ Message attendu:</strong> \"User linekode_admin has been added to database linekode_admin\"";
echo "</div>";
echo "</div>";
echo "<div>";
echo "<div class='image-placeholder'>";
echo "📸 Image: Page des permissions MySQL";
echo "<br><small>Case à cocher ALL PRIVILEGES et bouton Make Changes</small>";
echo "</div>";
echo "</div>";
echo "</div>";
echo "</div>";

echo "<div class='step'>";
echo "<div class='step-number'>6</div>";
echo "<h3>✅ Vérification finale</h3>";
echo "<p>Vérifiez que tout est bien configuré:</p>";
echo "<ul class='checklist'>";
echo "<li>Base de données <code>linekode_admin</code> existe</li>";
echo "<li>Utilisateur <code>linekode_admin</code> existe</li>";
echo "<li>L'utilisateur est bien associé à la base de données</li>";
echo "<li>Permissions ALL PRIVILEGES accordées</li>";
echo "</ul>";
echo "<div class='image-placeholder'>";
echo "📸 Image: Liste des bases de données et utilisateurs";
echo "<br><small>Vérification visuelle de la configuration complète</small>";
echo "</div>";
echo "</div>";

echo "<div class='step'>";
echo "<div class='step-number'>7</div>";
echo "<h3>🚀 Installation automatique</h3>";
echo "<p>Maintenant, lancez l'installation:</p>";
echo "<ol>";
echo "<li>Accédez à <a href='setup-server.php' class='btn btn-success'>setup-server.php</a></li>";
echo "<li>Le système détectera votre configuration</li>";
echo "<li>Suivez les instructions</li>";
echo "<li>Accédez à l'admin: <a href='login.php' class='btn'>login.php</a></li>";
echo "</ol>";
echo "<div class='success'>";
echo "<strong>🎉 Félicitations!</strong> Votre base de données est prête pour Linekode Admin!";
echo "</div>";
echo "</div>";

echo "<div class='warning'>";
echo "<h3>🔧 Dépannage rapide:</h3>";
echo "<ul>";
echo "<li><strong>Erreur de connexion:</strong> Vérifiez les identifiants exacts</li>";
echo "<li><strong>Permissions refusées:</strong> Re-cochez ALL PRIVILEGES</li>";
echo "<li><strong>Base non trouvée:</strong> Vérifiez l'orthographe exacte</li>";
echo "<li><strong>Mot de passe:</strong> Utilisez <code>linekode2024</code> exactement</li>";
echo "</ul>";
echo "</div>";

echo "<div style='margin-top: 50px; text-align: center;'>";
echo "<a href='setup-server.php' class='btn btn-success' style='font-size: 18px; padding: 18px 36px;'>🚀 Lancer l'installation maintenant</a>";
echo "<br><br>";
echo "<a href='login.php' class='btn'>🔐 Accès admin</a>";
echo "<a href='../index.html' class='btn'>🏠 Retour au site</a>";
echo "</div>";

echo "</body>";
echo "</html>";
?>
