<?php
// Guide complet de configuration SQL - Linekode Admin
echo "<!DOCTYPE html>";
echo "<html lang='fr'>";
echo "<head>";
echo "    <meta charset='UTF-8'>";
echo "    <meta name='viewport' content='width=device-width, initial-scale=1.0'>";
echo "    <title>Guide SQL Complet - Linekode Admin</title>";
echo "    <style>";
echo "        body { font-family: Arial, sans-serif; max-width: 1000px; margin: 40px auto; padding: 20px; }";
echo "        .header { background: linear-gradient(135deg, #28a745, #20c997); color: white; padding: 40px; border-radius: 15px; text-align: center; margin-bottom: 40px; }";
echo "        .method { border: 1px solid #ddd; padding: 30px; margin: 30px 0; border-radius: 15px; background: #f8f9fa; box-shadow: 0 4px 15px rgba(0,0,0,0.1); }";
echo "        .method h3 { color: #28a745; margin-top: 0; font-size: 28px; }";
echo "        .step-number { background: #28a745; color: white; width: 50px; height: 50px; border-radius: 50%; display: flex; align-items: center; justify-content: center; font-weight: bold; font-size: 24px; margin-bottom: 20px; }";
echo "        .code-block { background: #1e1e1e; color: #d4d4d4; padding: 20px; border-radius: 8px; font-family: 'Courier New', monospace; margin: 15px 0; overflow-x: auto; border: 2px solid #28a745; }";
echo "        .code-block.sql { background: #2d2d30; color: #d4d4d4; }";
echo "        .success { background: #d4edda; color: #155724; padding: 20px; border-radius: 10px; margin: 15px 0; border-left: 5px solid #28a745; }";
echo "        .info { background: #d1ecf1; color: #0c5460; padding: 20px; border-radius: 10px; margin: 15px 0; border-left: 5px solid #0284c7; }";
echo "        .warning { background: #fff3cd; color: #856404; padding: 20px; border-radius: 10px; margin: 15px 0; border-left: 5px solid #ffc107; }";
echo "        .error { background: #f8d7da; color: #721c24; padding: 20px; border-radius: 10px; margin: 15px 0; border-left: 5px solid #dc3545; }";
echo "        .btn { background: #28a745; color: white; padding: 15px 30px; border: none; border-radius: 8px; cursor: pointer; margin: 5px; text-decoration: none; display: inline-block; font-size: 16px; }";
echo "        .btn:hover { background: #218838; }";
echo "        .btn-primary { background: #0284c7; }";
echo "        .btn-primary:hover { background: #0369a1; }";
echo "        .btn-warning { background: #ffc107; color: #212529; }";
echo "        .btn-warning:hover { background: #e0a800; }";
echo "        .btn-danger { background: #dc3545; }";
echo "        .btn-danger:hover { background: #c82333; }";
echo "        .copy-btn { background: #ffc107; color: #212529; padding: 8px 16px; border: none; border-radius: 4px; cursor: pointer; margin: 5px; font-size: 14px; }";
echo "        .copy-btn:hover { background: #e0a800; }";
echo "        .checklist { list-style: none; padding: 0; }";
echo "        .checklist li { padding: 10px 0; border-bottom: 1px solid #eee; }";
echo "        .checklist li:before { content: '✅ '; margin-right: 8px; }";
echo "        .highlight { background: #fff3cd; padding: 20px; border-radius: 10px; border-left: 5px solid #ffc107; margin: 20px 0; }";
echo "        .two-columns { display: grid; grid-template-columns: 1fr 1fr; gap: 30px; align-items: start; }";
echo "        .progress-bar { background: #e9ecef; border-radius: 10px; overflow: hidden; margin: 20px 0; }";
echo "        .progress-fill { background: #28a745; height: 30px; line-height: 30px; text-align: center; color: white; font-weight: bold; transition: width 0.5s ease; }";
echo "    </style>";
echo "</head>";
echo "<body>";

echo "<div class='header'>";
echo "    <h1>🗄️ Guide SQL Complet</h1>";
echo "    <h2>Configuration Base de Données Linekode Admin</h2>";
echo "    <p>Suivez ce guide pour configurer votre base de données MySQL</p>";
echo "</div>";

echo "<div class='info'>";
echo "<h3>📋 Ce que nous allons configurer:</h3>";
echo "<ul class='checklist'>";
echo "<li>Base de données: <strong>linekode_admin</strong></li>";
echo "<li>Utilisateur: <strong>linekode_admin</strong></li>";
echo "<li>Mot de passe: <strong>linekode2024</strong></li>";
echo "<li>5 tables: inscriptions, annonces, messages, admin_users, settings, formations</li>";
echo "<li>Données initiales: utilisateur admin, formations par défaut</li>";
echo "<li>Permissions: Tous les privilèges</li>";
echo "</ul>";
echo "</div>";

echo "<div class='method'>";
echo "<h3>🚀 Méthode 1: phpMyAdmin (Recommandée)</h3>";
echo "<div class='two-columns'>";
echo "<div>";
echo "<ol>";
echo "<li><strong>Connectez-vous</strong> à phpMyAdmin</li>";
echo "<li><strong>Cliquez</strong> sur l'onglet <strong>SQL</strong></li>";
echo "<li><strong>Copiez</strong> tout le script ci-dessous</li>";
echo "<li><strong>Collez</strong> dans la zone de texte</li>";
echo "<li><strong>Cliquez</strong> sur <strong>Exécuter</strong></li>";
echo "</ol>";
echo "<div class='highlight'>";
echo "<strong>💡 Astuce:</strong> Assurez-vous d'être connecté avec un utilisateur qui a les droits CREATE USER (généralement root).";
echo "</div>";
echo "</div>";
echo "<div>";
echo "<div class='code-block sql'>";
echo "-- Script SQL complet pour Linekode Admin";
echo "-- Copiez tout ce bloc et exécutez-le dans phpMyAdmin";
echo "";
echo "-- 1. Créer la base de données";
echo "CREATE DATABASE IF NOT EXISTS linekode_admin;";
echo "USE linekode_admin;";
echo "";
echo "-- 2. Créer l'utilisateur admin";
echo "CREATE USER IF NOT EXISTS 'linekode_admin'@'localhost' IDENTIFIED BY 'linekode2024';";
echo "GRANT ALL PRIVILEGES ON linekode_admin.* TO 'linekode_admin'@'localhost';";
echo "FLUSH PRIVILEGES;";
echo "";
echo "-- 3. Créer les tables";
echo "CREATE TABLE IF NOT EXISTS inscriptions (";
echo "    id INT AUTO_INCREMENT PRIMARY KEY,";
echo "    name VARCHAR(255) NOT NULL,";
echo "    email VARCHAR(255) NOT NULL,";
echo "    phone VARCHAR(20),";
echo "    formation VARCHAR(255),";
echo "    niveau VARCHAR(50),";
echo "    motivation TEXT,";
echo "    address TEXT,";
echo "    status ENUM('new', 'pending', 'confirmed', 'cancelled') DEFAULT 'new',";
echo "    date DATE,";
echo "    source VARCHAR(50) DEFAULT 'admin',";
echo "    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,";
echo "    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP";
echo ");";
echo "";
echo "CREATE TABLE IF NOT EXISTS annonces (";
echo "    id INT AUTO_INCREMENT PRIMARY KEY,";
echo "    title VARCHAR(255) NOT NULL,";
echo "    content TEXT,";
echo "    status ENUM('draft', 'published', 'scheduled') DEFAULT 'draft',";
echo "    date DATE,";
echo "    author VARCHAR(100) DEFAULT 'Admin',";
echo "    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,";
echo "    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP";
echo ");";
echo "";
echo "CREATE TABLE IF NOT EXISTS messages (";
echo "    id INT AUTO_INCREMENT PRIMARY KEY,";
echo "    sender VARCHAR(255) NOT NULL,";
echo "    email VARCHAR(255) NOT NULL,";
echo "    phone VARCHAR(20),";
echo "    subject VARCHAR(255),";
echo "    content TEXT,";
echo "    date DATETIME,";
echo "    read_status BOOLEAN DEFAULT 0,";
echo "    source VARCHAR(50) DEFAULT 'admin',";
echo "    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP";
echo ");";
echo "";
echo "CREATE TABLE IF NOT EXISTS admin_users (";
echo "    id INT AUTO_INCREMENT PRIMARY KEY,";
echo "    username VARCHAR(50) UNIQUE NOT NULL,";
echo "    password VARCHAR(255) NOT NULL,";
echo "    email VARCHAR(255),";
echo "    last_login TIMESTAMP NULL,";
echo "    remember_token VARCHAR(255) NULL,";
echo "    token_expires TIMESTAMP NULL,";
echo "    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP";
echo ");";
echo "";
echo "CREATE TABLE IF NOT EXISTS settings (";
echo "    id INT AUTO_INCREMENT PRIMARY KEY,";
echo "    setting_key VARCHAR(100) UNIQUE NOT NULL,";
echo "    setting_value TEXT,";
echo "    description TEXT,";
echo "    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP";
echo ");";
echo "";
echo "CREATE TABLE IF NOT EXISTS formations (";
echo "    id INT AUTO_INCREMENT PRIMARY KEY,";
echo "    title VARCHAR(255) NOT NULL,";
echo "    description TEXT NOT NULL,";
echo "    duration VARCHAR(50),";
echo "    price VARCHAR(50),";
echo "    level ENUM('debutant', 'intermediaire', 'avance') DEFAULT 'debutant',";
echo "    status ENUM('active', 'inactive') DEFAULT 'active',";
echo "    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,";
echo "    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP";
echo ");";
echo "";
echo "-- 4. Insérer les données initiales";
echo "INSERT IGNORE INTO admin_users (username, password, email) VALUES ";
echo "    ('admin', '\$2y\$10\$92Vx0W3K9aL5q7nB6qD5s2E5J6Qw5J2n5J6Qw5', 'admin@linekode.sn');";
echo "";
echo "INSERT IGNORE INTO settings (setting_key, setting_value, description) VALUES ";
echo "    ('site_name', 'Linekode', 'Nom du site'),";
echo "    ('admin_email', 'admin@linekode.sn', 'Email de l\\'administrateur'),";
echo "    ('currency', 'FCFA', 'Devise monnaie'),";
echo "    ('company_name', 'Linekode Sénégal', 'Nom de l\\'entreprise'),";
echo "    ('company_phone', '+221 71 117 93 93', 'Téléphone'),";
echo "    ('company_address', 'Dakar, Sénégal', 'Adresse');";
echo "";
echo "INSERT IGNORE INTO annonces (title, content, status, date, author) VALUES ";
echo "    ('Bienvenue sur Linekode', 'Nous sommes ravis de vous accueillir dans notre école de formation en développement web.', 'published', CURDATE(), 'Admin');";
echo "";
echo "INSERT IGNORE INTO formations (title, description, duration, price, level, status) VALUES ";
echo "('Développement Web Frontend', 'Apprenez HTML, CSS, JavaScript et les frameworks modernes comme React et Vue.js pour créer des interfaces web interactives et responsives.', '3 mois', '50 000 FCFA', 'debutant', 'active'),";
echo "('Développement Web Backend', 'Maîtrisez PHP, MySQL, Node.js et les API REST pour créer des applications web robustes et performantes.', '3 mois', '50 000 FCFA', 'intermediaire', 'active'),";
echo "('Applications Mobiles', 'Développez des applications natives et hybrides pour iOS et Android avec React Native et Flutter.', '4 mois', '75 000 FCFA', 'intermediaire', 'active'),";
echo "('UI/UX Design', 'Apprenez les principes du design d\\'interface et d\\'expérience utilisateur avec Figma, Adobe XD et les meilleures pratiques.', '2 mois', '40 000 FCFA', 'debutant', 'active'),";
echo "('Base de Données Avancées', 'Approfondissez vos connaissances en SQL, NoSQL, optimisation et administration de bases de données.', '2 mois', '45 000 FCFA', 'avance', 'active');";
echo "";
echo "-- 5. Créer les index pour optimiser les performances";
echo "CREATE INDEX IF NOT EXISTS idx_inscriptions_status ON inscriptions(status);";
echo "CREATE INDEX IF NOT EXISTS idx_inscriptions_date ON inscriptions(date);";
echo "CREATE INDEX IF NOT EXISTS idx_messages_read_status ON messages(read_status);";
echo "CREATE INDEX IF NOT EXISTS idx_messages_date ON messages(date);";
echo "CREATE INDEX IF NOT EXISTS idx_annonces_status ON annonces(status);";
echo "CREATE INDEX IF NOT EXISTS idx_annonces_date ON annonces(date);";
echo "CREATE INDEX IF NOT EXISTS idx_formations_status ON formations(status);";
echo "CREATE INDEX IF NOT EXISTS idx_formations_level ON formations(level);";
echo "CREATE INDEX IF NOT EXISTS idx_formations_created_at ON formations(created_at);";
echo "";
echo "-- 6. Afficher les informations de configuration";
echo "SELECT 'Database: linekode_admin' as db_info,";
echo "       'User: linekode_admin@localhost' as user_info,";
echo "       'Tables créées: 6' as tables_count,";
echo "       'Permissions: GRANTED' as permissions;";
echo "</div>";
echo "<button class='copy-btn' onclick='copyFullScript()'>📋 Copier tout le script</button>";
echo "</div>";
echo "</div>";
echo "</div>";

echo "<div class='method'>";
echo "<h3>🖥️ Méthode 2: Ligne de commande MySQL</h3>";
echo "<ol>";
echo "<li><strong>Connectez-vous</strong> à votre serveur via SSH</li>";
echo "<li><strong>Connectez-vous</strong> à MySQL avec:</li>";
echo "</ol>";
echo "<div class='code-block'>";
echo "mysql -u root -p";
echo "</div>";
echo "<ol start='3'>";
echo "<li><strong>Créez</strong> le fichier SQL sur votre serveur:</li>";
echo "</ol>";
echo "<div class='code-block'>";
echo "nano linekode_setup.sql";
echo "</div>";
echo "<ol start='4'>";
echo "<li><strong>Collez</strong> le script SQL complet</li>";
echo "<li><strong>Sauvegardez</strong> (Ctrl+X, Y, Enter)</li>";
echo "<li><strong>Exécutez</strong> le script:</li>";
echo "</ol>";
echo "<div class='code-block'>";
echo "mysql -u root -p < linekode_setup.sql";
echo "</div>";
echo "</div>";

echo "<div class='method'>";
echo "<h3>🔧 Méthode 3: cPanel</h3>";
echo "<ol>";
echo "<li><strong>Connectez-vous</strong> à votre cPanel</li>";
echo "<li><strong>Allez</strong> dans <strong>MySQL Databases</strong></li>";
echo "<li><strong>Créez</strong> la base de données <code>linekode_admin</code></li>";
echo "<li><strong>Créez</strong> l'utilisateur <code>linekode_admin</code></li>";
echo "<li><strong>Donnez</strong> tous les privilèges sur la base de données</li>";
echo "<li><strong>Allez</strong> dans <strong>phpMyAdmin</strong></li>";
echo "<li><strong>Sélectionnez</strong> la base <code>linekode_admin</code></li>";
echo "<li><strong>Cliquez</strong> sur <strong>Importer</strong></li>";
echo "<li><strong>Sélectionnez</strong> le fichier <code>database-setup.sql</code></li>";
echo "<li><strong>Cliquez</strong> sur <strong>Exécuter</strong></li>";
echo "</ol>";
echo "</div>";

echo "<div class='method'>";
echo "<h3>🔍 Méthode 4: Installation Automatique</h3>";
echo "<p>Si vous préférez une installation automatique:</p>";
echo "<ol>";
echo "<li><strong>Assurez-vous</strong> d'avoir créé l'utilisateur MySQL</li>";
echo "<li><strong>Accédez</strong> à: <a href='setup-server.php' class='btn btn-primary'>setup-server.php</a></li>";
echo "<li><strong>Suivez</strong> les instructions automatiques</li>";
echo "<li><strong>Vérifiez</strong> que tout est bien configuré</li>";
echo "</ol>";
echo "</div>";

echo "<div class='success'>";
echo "<h3>✅ Messages de succès attendus:</h3>";
echo "<ul>";
echo "<li><strong>Base de données créée</strong>: Database linekode_admin created successfully</li>";
echo "<li><strong>Utilisateur créé</strong>: User linekode_admin created successfully</li>";
echo "<li><strong>Permissions accordées</strong>: Privileges granted successfully</li>";
echo "<li><strong>Tables créées</strong>: Query OK pour chaque CREATE TABLE</li>";
echo "<li><strong>Données insérées</strong>: Query OK pour chaque INSERT</li>";
echo "</ul>";
echo "</div>";

echo "<div class='warning'>";
echo "<h3>⚠️ Erreurs possibles et solutions:</h3>";
echo "<ul>";
echo "<li><strong>Access denied</strong>: Connectez-vous avec root ou un utilisateur admin</li>";
echo "<li><strong>CREATE USER privilege</strong>: Utilisez un utilisateur avec droits admin</li>";
echo "<li><strong>Database exists</strong>: Normal avec IF NOT EXISTS</li>";
echo "<li><strong>Table exists</strong>: Normal avec IF NOT EXISTS</li>";
echo "<li><strong>Duplicate entry</strong>: Normal avec INSERT IGNORE</li>";
echo "</ul>";
echo "</div>";

echo "<div class='info'>";
echo "<h3>🔍 Vérification après installation:</h3>";
echo "<p>Après exécution du script, vous devriez voir:</p>";
echo "<div class='code-block'>";
echo "+----------------------+----------------------+--------------+";
echo "| db_info              | user_info             | tables_count |";
echo "+----------------------+----------------------+--------------+";
echo "| Database: linekode_admin | User: linekode_admin@localhost | 6        |";
echo "+----------------------+----------------------+--------------+";
echo "</div>";
echo "</div>";

echo "<div class='method'>";
echo "<h3>🎯 Prochaines étapes après configuration SQL:</h3>";
echo "<ol>";
echo "<li><strong>Testez</strong> la connexion: <a href='login.php' class='btn btn-primary'>login.php</a></li>";
echo "<li><strong>Identifiants</strong>: admin / linekode2024</li>";
echo "<li><strong>Accédez</strong> au menu: <a href='menu-admin.php' class='btn btn-primary'>menu-admin.php</a></li>";
echo "<li><strong>Gérez</strong> le contenu: <a href='gestion-contenu.php' class='btn btn-primary'>gestion-contenu.php</a></li>";
echo "</ol>";
echo "</div>";

echo "<div style='margin-top: 50px; text-align: center;'>";
echo "<a href='setup-server.php' class='btn btn-success' style='font-size: 18px; padding: 18px 36px;'>🚀 Installation Automatique</a>";
echo "<br><br>";
echo "<a href='login.php' class='btn btn-primary'>🔐 Test de Connexion</a>";
echo "<a href='menu-admin.php' class='btn btn-primary'>🎛️ Menu Admin</a>";
echo "<a href='../index.html' class='btn'>🏠 Retour au site</a>";
echo "</div>";

echo "<script>";
echo "function copyFullScript() {";
echo "    const script = `-- Script SQL complet pour Linekode Admin";
echo "-- Copiez tout ce bloc et exécutez-le dans phpMyAdmin";
echo "";
echo "-- 1. Créer la base de données";
echo "CREATE DATABASE IF NOT EXISTS linekode_admin;";
echo "USE linekode_admin;";
echo "";
echo "-- 2. Créer l'utilisateur admin";
echo "CREATE USER IF NOT EXISTS 'linekode_admin'@'localhost' IDENTIFIED BY 'linekode2024';";
echo "GRANT ALL PRIVILEGES ON linekode_admin.* TO 'linekode_admin'@'localhost';";
echo "FLUSH PRIVILEGES;";
echo "";
echo "-- 3. Créer les tables";
echo "CREATE TABLE IF NOT EXISTS inscriptions (";
echo "    id INT AUTO_INCREMENT PRIMARY KEY,";
echo "    name VARCHAR(255) NOT NULL,";
echo "    email VARCHAR(255) NOT NULL,";
echo "    phone VARCHAR(20),";
echo "    formation VARCHAR(255),";
echo "    niveau VARCHAR(50),";
echo "    motivation TEXT,";
echo "    address TEXT,";
echo "    status ENUM('new', 'pending', 'confirmed', 'cancelled') DEFAULT 'new',";
echo "    date DATE,";
echo "    source VARCHAR(50) DEFAULT 'admin',";
echo "    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,";
echo "    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP";
echo ");";
echo "";
echo "CREATE TABLE IF NOT EXISTS annonces (";
echo "    id INT AUTO_INCREMENT PRIMARY KEY,";
echo "    title VARCHAR(255) NOT NULL,";
echo "    content TEXT,";
echo "    status ENUM('draft', 'published', 'scheduled') DEFAULT 'draft',";
echo "    date DATE,";
echo "    author VARCHAR(100) DEFAULT 'Admin',";
echo "    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,";
echo "    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP";
echo ");";
echo "";
echo "CREATE TABLE IF NOT EXISTS messages (";
echo "    id INT AUTO_INCREMENT PRIMARY KEY,";
echo "    sender VARCHAR(255) NOT NULL,";
echo "    email VARCHAR(255) NOT NULL,";
echo "    phone VARCHAR(20),";
echo "    subject VARCHAR(255),";
echo "    content TEXT,";
echo "    date DATETIME,";
echo "    read_status BOOLEAN DEFAULT 0,";
echo "    source VARCHAR(50) DEFAULT 'admin',";
echo "    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP";
echo ");";
echo "";
echo "CREATE TABLE IF NOT EXISTS admin_users (";
echo "    id INT AUTO_INCREMENT PRIMARY KEY,";
echo "    username VARCHAR(50) UNIQUE NOT NULL,";
echo "    password VARCHAR(255) NOT NULL,";
echo "    email VARCHAR(255),";
echo "    last_login TIMESTAMP NULL,";
echo "    remember_token VARCHAR(255) NULL,";
echo "    token_expires TIMESTAMP NULL,";
echo "    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP";
echo ");";
echo "";
echo "CREATE TABLE IF NOT EXISTS settings (";
echo "    id INT AUTO_INCREMENT PRIMARY KEY,";
echo "    setting_key VARCHAR(100) UNIQUE NOT NULL,";
echo "    setting_value TEXT,";
echo "    description TEXT,";
echo "    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP";
echo ");";
echo "";
echo "CREATE TABLE IF NOT EXISTS formations (";
echo "    id INT AUTO_INCREMENT PRIMARY KEY,";
echo "    title VARCHAR(255) NOT NULL,";
echo "    description TEXT NOT NULL,";
echo "    duration VARCHAR(50),";
echo "    price VARCHAR(50),";
echo "    level ENUM('debutant', 'intermediaire', 'avance') DEFAULT 'debutant',";
echo "    status ENUM('active', 'inactive') DEFAULT 'active',";
echo "    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,";
echo "    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP";
echo ");";
echo "";
echo "-- 4. Insérer les données initiales";
echo "INSERT IGNORE INTO admin_users (username, password, email) VALUES ";
echo "    ('admin', '\$2y\$10\$92Vx0W3K9aL5q7nB6qD5s2E5J6Qw5J2n5J6Qw5', 'admin@linekode.sn');";
echo "";
echo "INSERT IGNORE INTO settings (setting_key, setting_value, description) VALUES ";
echo "    ('site_name', 'Linekode', 'Nom du site'),";
echo "    ('admin_email', 'admin@linekode.sn', 'Email de l\\'administrateur'),";
echo "    ('currency', 'FCFA', 'Devise monnaie'),";
echo "    ('company_name', 'Linekode Sénégal', 'Nom de l\\'entreprise'),";
echo "    ('company_phone', '+221 71 117 93 93', 'Téléphone'),";
echo "    ('company_address', 'Dakar, Sénégal', 'Adresse');";
echo "";
echo "INSERT IGNORE INTO annonces (title, content, status, date, author) VALUES ";
echo "    ('Bienvenue sur Linekode', 'Nous sommes ravis de vous accueillir dans notre école de formation en développement web.', 'published', CURDATE(), 'Admin');";
echo "";
echo "INSERT IGNORE INTO formations (title, description, duration, price, level, status) VALUES ";
echo "('Développement Web Frontend', 'Apprenez HTML, CSS, JavaScript et les frameworks modernes comme React et Vue.js pour créer des interfaces web interactives et responsives.', '3 mois', '50 000 FCFA', 'debutant', 'active'),";
echo "('Développement Web Backend', 'Maîtrisez PHP, MySQL, Node.js et les API REST pour créer des applications web robustes et performantes.', '3 mois', '50 000 FCFA', 'intermediaire', 'active'),";
echo "('Applications Mobiles', 'Développez des applications natives et hybrides pour iOS et Android avec React Native et Flutter.', '4 mois', '75 000 FCFA', 'intermediaire', 'active'),";
echo "('UI/UX Design', 'Apprenez les principes du design d\\'interface et d\\'expérience utilisateur avec Figma, Adobe XD et les meilleures pratiques.', '2 mois', '40 000 FCFA', 'debutant', 'active'),";
echo "('Base de Données Avancées', 'Approfondissez vos connaissances en SQL, NoSQL, optimisation et administration de bases de données.', '2 mois', '45 000 FCFA', 'avance', 'active');";
echo "";
echo "-- 5. Créer les index pour optimiser les performances";
echo "CREATE INDEX IF NOT EXISTS idx_inscriptions_status ON inscriptions(status);";
echo "CREATE INDEX IF NOT EXISTS idx_inscriptions_date ON inscriptions(date);";
echo "CREATE INDEX IF NOT EXISTS idx_messages_read_status ON messages(read_status);";
echo "CREATE INDEX IF NOT EXISTS idx_messages_date ON messages(date);";
echo "CREATE INDEX IF NOT EXISTS idx_annonces_status ON annonces(status);";
echo "CREATE INDEX IF NOT EXISTS idx_annonces_date ON annonces(date);";
echo "CREATE INDEX IF NOT EXISTS idx_formations_status ON formations(status);";
echo "CREATE INDEX IF NOT EXISTS idx_formations_level ON formations(level);";
echo "CREATE INDEX IF NOT EXISTS idx_formations_created_at ON formations(created_at);";
echo "";
echo "-- 6. Afficher les informations de configuration";
echo "SELECT 'Database: linekode_admin' as db_info,";
echo "       'User: linekode_admin@localhost' as user_info,";
echo "       'Tables créées: 6' as tables_count,";
echo "       'Permissions: GRANTED' as permissions;`;";
echo "    navigator.clipboard.writeText(script);";
echo "    alert('Script SQL copié dans le presse-papier!');";
echo "}";
echo "</script>";

echo "</body>";
echo "</html>";
?>
