<?php
// Guide détaillé phpMyAdmin - Linekode Admin
echo "<!DOCTYPE html>";
echo "<html lang='fr'>";
echo "<head>";
echo "    <meta charset='UTF-8'>";
echo "    <meta name='viewport' content='width=device-width, initial-scale=1.0'>";
echo "    <title>Guide phpMyAdmin - Linekode Admin</title>";
echo "    <style>";
echo "        body { font-family: Arial, sans-serif; max-width: 1000px; margin: 40px auto; padding: 20px; }";
echo "        .header { background: linear-gradient(135deg, #ff6b35, #f7931e); color: white; padding: 40px; border-radius: 15px; text-align: center; margin-bottom: 40px; }";
echo "        .step { border: 1px solid #ddd; padding: 30px; margin: 30px 0; border-radius: 15px; background: #f8f9fa; box-shadow: 0 4px 15px rgba(0,0,0,0.1); }";
echo "        .step h3 { color: #ff6b35; margin-top: 0; font-size: 28px; }";
echo "        .step-number { background: #ff6b35; color: white; width: 50px; height: 50px; border-radius: 50%; display: flex; align-items: center; justify-content: center; font-weight: bold; font-size: 24px; margin-bottom: 20px; }";
echo "        .image-placeholder { background: #e9ecef; border: 2px dashed #adb5bd; border-radius: 10px; padding: 40px; text-align: center; margin: 20px 0; color: #6c757d; }";
echo "        .code-block { background: #1e1e1e; color: #d4d4d4; padding: 20px; border-radius: 8px; font-family: 'Courier New', monospace; margin: 15px 0; overflow-x: auto; }";
echo "        .code-block.sql { background: #2d2d30; color: #d4d4d4; }";
echo "        .success { background: #d4edda; color: #155724; padding: 20px; border-radius: 10px; margin: 15px 0; border-left: 5px solid #28a745; }";
echo "        .info { background: #d1ecf1; color: #0c5460; padding: 20px; border-radius: 10px; margin: 15px 0; border-left: 5px solid #0284c7; }";
echo "        .warning { background: #fff3cd; color: #856404; padding: 20px; border-radius: 10px; margin: 15px 0; border-left: 5px solid #ffc107; }";
echo "        .btn { background: #ff6b35; color: white; padding: 15px 30px; border: none; border-radius: 8px; cursor: pointer; margin: 5px; text-decoration: none; display: inline-block; font-size: 16px; }";
echo "        .btn:hover { background: #e55a2b; }";
echo "        .btn-success { background: #28a745; }";
echo "        .btn-success:hover { background: #218838; }";
echo "        .btn-primary { background: #0284c7; }";
echo "        .btn-primary:hover { background: #0369a1; }";
echo "        .highlight { background: #fff3cd; padding: 20px; border-radius: 10px; border-left: 5px solid #ffc107; margin: 20px 0; }";
echo "        .checklist { list-style: none; padding: 0; }";
echo "        .checklist li { padding: 10px 0; border-bottom: 1px solid #eee; }";
echo "        .checklist li:before { content: '✅ '; margin-right: 8px; }";
echo "        .two-columns { display: grid; grid-template-columns: 1fr 1fr; gap: 30px; align-items: start; }";
echo "    </style>";
echo "</head>";
echo "<body>";

echo "<div class='header'>";
echo "    <h1>🌐 Guide phpMyAdmin</h1>";
echo "    <h2>Créer l'utilisateur MySQL pour Linekode Admin</h2>";
echo "    <p>Méthode 3 : Utilisation de phpMyAdmin</p>";
echo "</div>";

echo "<div class='info'>";
echo "<h3>📋 Ce que nous allons faire:</h3>";
echo "<ul class='checklist'>";
echo "<li>Se connecter à phpMyAdmin</li>";
echo "<li>Accéder à l'onglet SQL</li>";
echo "<li>Exécuter la commande de création d'utilisateur</li>";
echo "<li>Vérifier que l'utilisateur est bien créé</li>";
echo "</ul>";
echo "</div>";

echo "<div class='step'>";
echo "<div class='step-number'>1</div>";
echo "<h3>🔐 Accéder à phpMyAdmin</h3>";
echo "<div class='two-columns'>";
echo "<div>";
echo "<p><strong>URLs phpMyAdmin courantes:</strong></p>";
echo "<ul>";
echo "<li><code>https://votredomaine.com/phpmyadmin</code></li>";
echo "<li><code>https://votredomaine.com:2083/phpmyadmin</code></li>";
echo "<li><code>https://cpanel.votredomaine.com/phpmyadmin</code></li>";
echo "<li>Via cPanel → phpMyAdmin</li>";
echo "</ul>";
echo "<p><strong>Identifiants:</strong></p>";
echo "<ul>";
echo "<li>Utilisez vos identifiants cPanel/hébergeur</li>";
echo "<li>Ou les identifiants MySQL fournis</li>";
echo "</ul>";
echo "</div>";
echo "<div>";
echo "<div class='image-placeholder'>";
echo "📸 Image: Page de connexion phpMyAdmin";
echo "<br><small>Interface de connexion avec champs username/password</small>";
echo "</div>";
echo "</div>";
echo "</div>";
echo "</div>";

echo "<div class='step'>";
echo "<div class='step-number'>2</div>";
echo "<h3>📋 Accéder à l'onglet SQL</h3>";
echo "<div class='two-columns'>";
echo "<div>";
echo "<p>Une fois connecté à phpMyAdmin:</p>";
echo "<ol>";
echo "<li>Cherchez l'onglet <strong>SQL</strong> en haut</li>";
echo "<li>Cliquez sur l'onglet SQL</li>";
echo "<li>Vous verrez une grande zone de texte</li>";
echo "<li>C'est ici que nous allons coller notre commande</li>";
echo "</ol>";
echo "<div class='highlight'>";
echo "<strong>💡 Astuce:</strong> L'onglet SQL est généralement dans la barre supérieure avec les autres onglets comme Structure, SQL, Search, etc.";
echo "</div>";
echo "</div>";
echo "<div>";
echo "<div class='image-placeholder'>";
echo "📸 Image: Interface phpMyAdmin";
echo "<br><small>Onglet SQL surligné en rouge avec zone de texte</small>";
echo "</div>";
echo "</div>";
echo "</div>";
echo "</div>";

echo "<div class='step'>";
echo "<div class='step-number'>3</div>";
echo "<h3>💻 Coller la commande SQL</h3>";
echo "<div class='two-columns'>";
echo "<div>";
echo "<p>Dans la zone de texte SQL, collez cette commande:</p>";
echo "<div class='code-block sql'>";
echo "CREATE USER IF NOT EXISTS 'linekode_admin'@'localhost' IDENTIFIED BY 'linekode2024';";
echo "</div>";
echo "<p><strong>Important:</strong></p>";
echo "<ul>";
echo "<li>Copiez la commande exactement comme elle est</li>";
echo "<li>Ne modifiez pas les guillemets</li>";
echo "<li>Assurez-vous que 'localhost' est bien entre guillemets</li>";
echo "</ul>";
echo "</div>";
echo "<div>";
echo "<div class='image-placeholder'>";
echo "📸 Image: Zone de texte SQL";
echo "<br><small>Commande SQL collée dans la zone de texte avec bouton Exécuter</small>";
echo "</div>";
echo "</div>";
echo "</div>";
echo "</div>";

echo "<div class='step'>";
echo "<div class='step-number'>4</div>";
echo "<h3>🚀 Exécuter la commande</h3>";
echo "<div class='two-columns'>";
echo "<div>";
echo "<p>Pour exécuter la commande:</p>";
echo "<ol>";
echo "<li>Vérifiez que la commande est bien collée</li>";
echo "<li>Cliquez sur le bouton <strong>Exécuter</strong> (ou Go)</li>";
echo "<li>Attendez le résultat</li>";
echo "</ol>";
echo "<p><strong>Message de succès attendu:</strong></p>";
echo "<div class='success'>";
echo "<code># Query OK, 0 rows affected</code>";
echo "</div>";
echo "<p><strong>Si vous voyez ce message, l'utilisateur est créé!</strong></p>";
echo "</div>";
echo "<div>";
echo "<div class='image-placeholder'>";
echo "📸 Image: Bouton Exécuter";
echo "<br><small>Bouton Exécuter/Go surligné avec message de succès</small>";
echo "</div>";
echo "</div>";
echo "</div>";
echo "</div>";

echo "<div class='step'>";
echo "<div class='step-number'>5</div>";
echo "<h3>🔐 Donner les permissions</h3>";
echo "<div class='two-columns'>";
echo "<div>";
echo "<p>Maintenant, nous devons donner les permissions à l'utilisateur:</p>";
echo "<ol>";
echo "<li>Restez dans l'onglet SQL</li>";
echo "<li>Collez cette commande:</li>";
echo "</ol>";
echo "<div class='code-block sql'>";
echo "GRANT ALL PRIVILEGES ON linekode_admin.* TO 'linekode_admin'@'localhost';";
echo "</div>";
echo "<ol start='3'>";
echo "<li>Cliquez sur <strong>Exécuter</strong></li>";
echo "<li>Message de succès attendu: <code># Query OK, 0 rows affected</code></li>";
echo "</ol>";
echo "</div>";
echo "<div>";
echo "<div class='image-placeholder'>";
echo "📸 Image: Commande GRANT";
echo "<br><small>Commande GRANT dans la zone SQL avec bouton Exécuter</small>";
echo "</div>";
echo "</div>";
echo "</div>";
echo "</div>";

echo "<div class='step'>";
echo "<div class='step-number'>6</div>";
echo "<h3>🔄 Appliquer les changements</h3>";
echo "<div class='two-columns'>";
echo "<div>";
echo "<p>Pour finaliser, appliquons les changements:</p>";
echo "<ol>";
echo "<li>Dans l'onglet SQL, collez:</li>";
echo "</ol>";
echo "<div class='code-block sql'>";
echo "FLUSH PRIVILEGES;";
echo "</div>";
echo "<ol start='2'>";
echo "<li>Cliquez sur <strong>Exécuter</strong></li>";
echo "<li>Message de succès: <code># Query OK, 0 rows affected</code></li>";
echo "</ol>";
echo "<div class='success'>";
echo "<strong>✅ Félicitations!</strong> L'utilisateur est maintenant créé avec toutes les permissions!";
echo "</div>";
echo "</div>";
echo "<div>";
echo "<div class='image-placeholder'>";
echo "📸 Image: Commande FLUSH PRIVILEGES";
echo "<br><small>Dernière commande avec message de succès final</small>";
echo "</div>";
echo "</div>";
echo "</div>";
echo "</div>";

echo "<div class='step'>";
echo "<div class='step-number'>7</div>";
echo "<h3>✅ Vérifier la création</h3>";
echo "<p>Pour vérifier que tout est bien configuré:</p>";
echo "<ol>";
echo "<li>Dans l'onglet SQL, collez cette commande:</li>";
echo "</ol>";
echo "<div class='code-block sql'>";
echo "SELECT User, Host FROM mysql.user WHERE User = 'linekode_admin';";
echo "</div>";
echo "<ol start='2'>";
echo "<li>Cliquez sur <strong>Exécuter</strong></li>";
echo "<li>Vous devriez voir:</li>";
echo "</ol>";
echo "<div class='success'>";
echo "<code>linekode_admin | localhost</code>";
echo "</div>";
echo "<p>Si vous voyez cette ligne, l'utilisateur est bien créé!</p>";
echo "</div>";

echo "<div class='step'>";
echo "<div class='step-number'>8</div>";
echo "<h3>🎉 Configuration terminée!</h3>";
echo "<div class='success'>";
echo "<h3>✅ Succès!</h3>";
echo "<p>Vous avez créé avec succès:</p>";
echo "<ul>";
echo "<li>Utilisateur: <strong>linekode_admin</strong></li>";
echo "<li>Mot de passe: <strong>linekode2024</strong></li>";
echo "<li>Permissions: <strong>Tous les privilèges</strong></li>";
echo "<li>Base de données: <strong>linekode_admin</strong></li>";
echo "</ul>";
echo "</div>";
echo "<p>Maintenant, vous pouvez:</p>";
echo "<ol>";
echo "<li>Accéder à l'installation: <a href='setup-server.php' class='btn btn-success'>setup-server.php</a></li>";
echo "<li>Vous connecter à l'admin: <a href='login.php' class='btn btn-primary'>login.php</a></li>";
echo "</ol>";
echo "</div>";

echo "<div class='warning'>";
echo "<h3>⚠️ Problèmes courants et solutions:</h3>";
echo "<ul>";
echo "<li><strong>Erreur de syntaxe:</strong> Vérifiez les guillemets et apostrophes</li>";
echo "<li><strong>Permissions refusées:</strong> Assurez-vous d'être connecté avec un utilisateur admin</li>";
echo "<li><strong>Utilisateur existe déjà:</strong> C'est normal, la commande contient IF NOT EXISTS</li>";
echo "<li><strong>Aucun résultat:</strong> Vérifiez que vous avez bien exécuté toutes les commandes</li>";
echo "</ul>";
echo "</div>";

echo "<div class='info'>";
echo "<h3>📋 Récapitulatif des commandes:</h3>";
echo "<div class='code-block sql'>";
echo "-- 1. Créer l'utilisateur";
echo "CREATE USER IF NOT EXISTS 'linekode_admin'@'localhost' IDENTIFIED BY 'linekode2024';";
echo "";
echo "-- 2. Donner les permissions";
echo "GRANT ALL PRIVILEGES ON linekode_admin.* TO 'linekode_admin'@'localhost';";
echo "";
echo "-- 3. Appliquer les changements";
echo "FLUSH PRIVILEGES;";
echo "";
echo "-- 4. Vérifier (optionnel)";
echo "SELECT User, Host FROM mysql.user WHERE User = 'linekode_admin';";
echo "</div>";
echo "</div>";

echo "<div style='margin-top: 50px; text-align: center;'>";
echo "<a href='setup-server.php' class='btn btn-success' style='font-size: 18px; padding: 18px 36px;'>🚀 Lancer l'installation maintenant</a>";
echo "<br><br>";
echo "<a href='login.php' class='btn btn-primary'>🔐 Accès admin</a>";
echo "<a href='../index.html' class='btn'>🏠 Retour au site</a>";
echo "</div>";

echo "</body>";
echo "</html>";
?>
