<?php
// Commandes MySQL complètes - Linekode Admin
echo "<!DOCTYPE html>";
echo "<html lang='fr'>";
echo "<head>";
echo "    <meta charset='UTF-8'>";
echo "    <meta name='viewport' content='width=device-width, initial-scale=1.0'>";
echo "    <title>Commandes MySQL - Linekode Admin</title>";
echo "    <style>";
echo "        body { font-family: Arial, sans-serif; max-width: 1000px; margin: 50px auto; padding: 20px; }";
echo "        .header { background: linear-gradient(135deg, #28a745, #20c997); color: white; padding: 30px; border-radius: 12px; text-align: center; margin-bottom: 30px; }";
echo "        .command-section { border: 1px solid #ddd; padding: 25px; margin: 20px 0; border-radius: 12px; background: #f8f9fa; }";
echo "        .command-section h3 { color: #28a745; margin-top: 0; }";
echo "        .code-block { background: #1e1e1e; color: #d4d4d4; padding: 20px; border-radius: 8px; font-family: 'Courier New', monospace; margin: 15px 0; overflow-x: auto; }";
echo "        .code-block.sql { background: #2d2d30; color: #d4d4d4; }";
echo "        .success { background: #d4edda; color: #155724; padding: 15px; border-radius: 8px; margin: 10px 0; border-left: 4px solid #28a745; }";
echo "        .info { background: #d1ecf1; color: #0c5460; padding: 15px; border-radius: 8px; margin: 10px 0; border-left: 4px solid #0284c7; }";
echo "        .warning { background: #fff3cd; color: #856404; padding: 15px; border-radius: 8px; margin: 10px 0; border-left: 4px solid #ffc107; }";
echo "        .btn { background: #28a745; color: white; padding: 12px 24px; border: none; border-radius: 6px; cursor: pointer; margin: 5px; text-decoration: none; display: inline-block; }";
echo "        .btn:hover { background: #218838; }";
echo "        .btn-primary { background: #0284c7; }";
echo "        .btn-primary:hover { background: #0369a1; }";
echo "        .step { display: flex; align-items: flex-start; margin: 15px 0; }";
echo "        .step-number { background: #28a745; color: white; width: 30px; height: 30px; border-radius: 50%; display: flex; align-items: center; justify-content: center; font-weight: bold; margin-right: 15px; flex-shrink: 0; }";
echo "        .step-content { flex: 1; }";
echo "    </style>";
echo "</head>";
echo "<body>";

echo "<div class='header'>";
echo "    <h1>💻 Commandes MySQL Complètes</h1>";
echo "    <h2>Linekode Admin - Configuration Base de Données</h2>";
echo "</div>";

echo "<div class='info'>";
echo "<h3>📋 Configuration requise:</h3>";
echo "<ul>";
echo "<li><strong>Base de données:</strong> linekode_admin</li>";
echo "<li><strong>Utilisateur:</strong> linekode_admin</li>";
echo "<li><strong>Mot de passe:</strong> linekode2024</li>";
echo "<li><strong>Permissions:</strong> Tous les privilèges</li>";
echo "</ul>";
echo "</div>";

echo "<div class='command-section'>";
echo "<h3>🗄️ Commandes complètes (à copier-coller)</h3>";
echo "<p>Voici toutes les commandes MySQL nécessaires pour configurer Linekode Admin:</p>";
echo "<div class='code-block sql'>";
echo "-- 1. Créer la base de données";
echo "CREATE DATABASE IF NOT EXISTS linekode_admin;";
echo "";
echo "-- 2. Créer l'utilisateur";
echo "CREATE USER IF NOT EXISTS 'linekode_admin'@'localhost' IDENTIFIED BY 'linekode2024';";
echo "";
echo "-- 3. Donner les permissions";
echo "GRANT ALL PRIVILEGES ON linekode_admin.* TO 'linekode_admin'@'localhost';";
echo "";
echo "-- 4. Appliquer les changements";
echo "FLUSH PRIVILEGES;";
echo "";
echo "-- 5. Vérifier (optionnel)";
echo "SHOW DATABASES;";
echo "SELECT User FROM mysql.user WHERE User = 'linekode_admin';";
echo "SHOW GRANTS FOR 'linekode_admin'@'localhost';";
echo "</div>";
echo "</div>";

echo "<div class='command-section'>";
echo "<h3>🖥️ Méthode 1: Terminal MySQL</h3>";
echo "<div class='step'>";
echo "<div class='step-number'>1</div>";
echo "<div class='step-content'>";
echo "<p>Connectez-vous à MySQL:</p>";
echo "<div class='code-block'>";
echo "mysql -u root -p";
echo "</div>";
echo "</div>";
echo "</div>";
echo "<div class='step'>";
echo "<div class='step-number'>2</div>";
echo "<div class='step-content'>";
echo "<p>Exécutez les commandes une par une:</p>";
echo "<div class='code-block sql'>";
echo "CREATE DATABASE IF NOT EXISTS linekode_admin;";
echo "CREATE USER IF NOT EXISTS 'linekode_admin'@'localhost' IDENTIFIED BY 'linekode2024';";
echo "GRANT ALL PRIVILEGES ON linekode_admin.* TO 'linekode_admin'@'localhost';";
echo "FLUSH PRIVILEGES;";
echo "</div>";
echo "</div>";
echo "</div>";
echo "<div class='step'>";
echo "<div class='step-number'>3</div>";
echo "<div class='step-content'>";
echo "<p>Quittez MySQL:</p>";
echo "<div class='code-block'>";
echo "EXIT;";
echo "</div>";
echo "</div>";
echo "</div>";
echo "</div>";

echo "<div class='command-section'>";
echo "<h3>🌐 Méthode 2: phpMyAdmin</h3>";
echo "<div class='step'>";
echo "<div class='step-number'>1</div>";
echo "<div class='step-content'>";
echo "<p>Connectez-vous à phpMyAdmin</p>";
echo "</div>";
echo "</div>";
echo "<div class='step'>";
echo "<div class='step-number'>2</div>";
echo "<div class='step-content'>";
echo "<p>Cliquez sur l'onglet <strong>SQL</strong></p>";
echo "</div>";
echo "</div>";
echo "<div class='step'>";
echo "<div class='step-number'>3</div>";
echo "<div class='step-content'>";
echo "<p>Collez et exécutez:</p>";
echo "<div class='code-block sql'>";
echo "CREATE DATABASE IF NOT EXISTS linekode_admin;";
echo "CREATE USER IF NOT EXISTS 'linekode_admin'@'localhost' IDENTIFIED BY 'linekode2024';";
echo "GRANT ALL PRIVILEGES ON linekode_admin.* TO 'linekode_admin'@'localhost';";
echo "FLUSH PRIVILEGES;";
echo "</div>";
echo "</div>";
echo "</div>";
echo "</div>";

echo "<div class='command-section'>";
echo "<h3>🔧 Méthode 3: SSH + MySQL</h3>";
echo "<div class='step'>";
echo "<div class='step-number'>1</div>";
echo "<div class='step-content'>";
echo "<p>Connectez-vous au serveur:</p>";
echo "<div class='code-block'>";
echo "ssh utilisateur@votre-serveur.com";
echo "</div>";
echo "</div>";
echo "</div>";
echo "<div class='step'>";
echo "<div class='step-number'>2</div>";
echo "<div class='step-content'>";
echo "<p>Connectez-vous à MySQL:</p>";
echo "<div class='code-block'>";
echo "mysql -u root -p";
echo "</div>";
echo "</div>";
echo "</div>";
echo "<div class='step'>";
echo "<div class='step-number'>3</div>";
echo "<div class='step-content'>";
echo "<p>Exécutez les commandes:</p>";
echo "<div class='code-block sql'>";
echo "CREATE DATABASE IF NOT EXISTS linekode_admin;";
echo "CREATE USER IF NOT EXISTS 'linekode_admin'@'localhost' IDENTIFIED BY 'linekode2024';";
echo "GRANT ALL PRIVILEGES ON linekode_admin.* TO 'linekode_admin'@'localhost';";
echo "FLUSH PRIVILEGES;";
echo "EXIT;";
echo "</div>";
echo "</div>";
echo "</div>";
echo "</div>";

echo "<div class='command-section'>";
echo "<h3>📋 Commandes de vérification</h3>";
echo "<p>Pour vérifier que tout est bien configuré:</p>";
echo "<div class='code-block sql'>";
echo "-- Vérifier la base de données";
echo "SHOW DATABASES LIKE 'linekode_admin';";
echo "";
echo "-- Vérifier l'utilisateur";
echo "SELECT User, Host FROM mysql.user WHERE User = 'linekode_admin';";
echo "";
echo "-- Vérifier les permissions";
echo "SHOW GRANTS FOR 'linekode_admin'@'localhost';";
echo "";
echo "-- Tester la connexion (optionnel)";
echo "mysql -u linekode_admin -plinekode2024 -e 'SHOW DATABASES;'";
echo "</div>";
echo "</div>";

echo "<div class='command-section'>";
echo "<h3>🔧 Dépannage</h3>";
echo "<h4>Si l'utilisateur existe déjà:</h4>";
echo "<div class='code-block sql'>";
echo "-- Supprimer l'utilisateur existant";
echo "DROP USER IF EXISTS 'linekode_admin'@'localhost';";
echo "-- Recréer l'utilisateur";
echo "CREATE USER 'linekode_admin'@'localhost' IDENTIFIED BY 'linekode2024';";
echo "GRANT ALL PRIVILEGES ON linekode_admin.* TO 'linekode_admin'@'localhost';";
echo "FLUSH PRIVILEGES;";
echo "</div>";
echo "<h4>Si les permissions ne fonctionnent pas:</h4>";
echo "<div class='code-block sql'>";
echo "-- Révoquer et redonner les permissions";
echo "REVOKE ALL PRIVILEGES ON linekode_admin.* FROM 'linekode_admin'@'localhost';";
echo "GRANT ALL PRIVILEGES ON linekode_admin.* TO 'linekode_admin'@'localhost';";
echo "FLUSH PRIVILEGES;";
echo "</div>";
echo "<h4>Si vous avez des erreurs d'accès:</h4>";
echo "<div class='code-block sql'>";
echo "-- Donner des permissions plus larges (si nécessaire)";
echo "GRANT ALL PRIVILEGES ON *.* TO 'linekode_admin'@'localhost';";
echo "FLUSH PRIVILEGES;";
echo "</div>";
echo "</div>";

echo "<div class='success'>";
echo "<h3>✅ Une fois les commandes exécutées:</h3>";
echo "<ol>";
echo "<li>Testez la connexion avec: <a href='create-user.php' class='btn'>create-user.php</a></li>";
echo "<li>Lancez l'installation: <a href='setup-server.php' class='btn btn-primary'>setup-server.php</a></li>";
echo "<li>Accédez à l'admin: <a href='login.php' class='btn btn-primary'>login.php</a></li>";
echo "</ol>";
echo "</div>";

echo "<div class='warning'>";
echo "<h3>⚠️ Notes importantes:</h3>";
echo "<ul>";
echo "<li>Remplacez <code>linekode2024</code> si vous utilisez un autre mot de passe</li>";
echo "<li>Assurez-vous que MySQL est en cours d'exécution</li>";
echo "<li>Vous avez besoin des droits root/administrateur pour exécuter ces commandes</li>";
echo "<li>Utilisez <code>FLUSH PRIVILEGES</code> après chaque modification de permissions</li>";
echo "</ul>";
echo "</div>";

echo "<div style='margin-top: 40px; text-align: center;'>";
echo "<a href='create-user.php' class='btn'>🚀 Création automatique</a>";
echo "<a href='setup-server.php' class='btn btn-primary'>🚀 Installation</a>";
echo "<a href='login.php' class='btn btn-primary'>🔐 Accès admin</a>";
echo "<a href='../index.html' class='btn'>🏠 Retour au site</a>";
echo "</div>";

echo "</body>";
echo "</html>";
?>
